# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
  - name: BUILD_NUMBER
    displayName: 'Build Number'
    type: string
    default: $[format('{0:yyyyMMdd}', pipeline.startTime)]

jobs:
- job: MsGraphDownloadOpenApiDocs
  displayName: Microsoft Graph PowerShell SDK Download OpenApiDocs Module Generation
  pool: MsGraphDevXAzureAgents
  timeoutInMinutes: 600

  steps:
  - checkout: self
    persistCredentials: true

  - template: ./install-tools-template.yml

  - task: PowerShell@2
    displayName: 'Download v1.0 OpenApiDocs'
    continueOnError: true
    condition: and(succeeded(), eq(eq(variables['Build.SourceBranch'], 'refs/heads/master'), false))
    inputs:
      targetType: 'filePath'
      pwsh: true
      filePath: '$(System.DefaultWorkingDirectory)/tools/UpdateOpenApi.ps1'
      

  - task: PowerShell@2
    displayName: 'Download beta OpenApiDocs'
    continueOnError: false
    condition: and(succeeded(), eq(eq(variables['Build.SourceBranch'], 'refs/heads/master'), false))
    inputs:
      targetType: 'filePath'
      pwsh: true
      filePath: '$(System.DefaultWorkingDirectory)/tools/UpdateOpenApi.ps1'
      arguments: > 
         -BetaGraphVersion

  - task: PowerShell@2
    displayName: "Configure User"
    condition: and(succeeded(), eq(eq(variables['Build.SourceBranch'], 'refs/heads/master'), false))
    inputs:
      targetType: 'inline'
      pwsh: true
      script: |
        git config --global user.email 'GraphTooling@service.microsoft.com'
        git config --global user.name 'Microsoft Graph DevX Tooling'

  - task: Bash@3
    condition: and(succeeded(), eq(eq(variables['Build.SourceBranch'], 'refs/heads/master'), false))
    env: 
      GITHUB_TOKEN: $(GITHUB_TOKEN)
    inputs:
      targetType: 'inline'
      script: |
        git status
        git checkout $(Build.SourceBranchName)
        git pull
        git add .
        git commit -m 'Release OpenApiDocs Download [skip ci]'
        git push --set-upstream origin $(Build.SourceBranchName)
        git status