# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
  - name: AUTH_MODULE_PATH
    displayName: 'Authentication Module Path'
    type: string
    default: 'src\Authentication\Authentication\'
  - name: AUTH_MODULE_NAME
    displayName: 'Authentication Module Name'
    type: string
    default: 'Authentication'
  - name: AUTH_MODULE_DLL_PATTERN
    displayName: 'Authentication Module DLL Pattern'
    type: string
    default: 'Microsoft.Graph.Authentication.dll'
  - name: Api_Key
    displayName: 'Api Key'
    type: string
  - name: EnableSigning
    displayName: 'Enable Signing'
    type: boolean
    default: false
  - name: BUILD_NUMBER
    displayName: 'Build Number'
    type: string
    default: $[format('{0:yyMMddHHmm}', pipeline.startTime)]

jobs:
- job: MsGraphPSSDKAuthModuleGeneration
  displayName: Microsoft Graph PowerShell SDK Auth Module Generation
  pool: MsGraphDevXAzureAgents
  
  steps:
  - template: ./install-tools-template.yml
  
  - task: PowerShell@2
    displayName: 'Generate and Build Auth Module'
    inputs:
      targetType: 'inline'
      pwsh: true
      script: |
        pwsh $(System.DefaultWorkingDirectory)/tools/GenerateAuthenticationModule.ps1 -ArtifactsLocation $(Build.ArtifactStagingDirectory) -Build -EnableSigning -ModulePreviewNumber $(BUILD_NUMBER)

  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP DLL Strong Name (Graph Auth Module)'
    enabled: true
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet (AKV)'
      FolderPath: $(AUTH_MODULE_PATH)
      Pattern: $(AUTH_MODULE_DLL_PATTERN)
      signConfigType: inlineSignParams
      inlineOperation: |
       [
           {
               "keyCode": "CP-233863-SN",
               "operationSetCode": "StrongNameSign",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           },
           {
               "keyCode": "CP-233863-SN",
               "operationSetCode": "StrongNameVerify",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           }
       ]
      SessionTimeout: 20
  
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP DLL CodeSigning (Graph Auth Module)'
    enabled: true
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet (AKV)'
      FolderPath: $(AUTH_MODULE_PATH)
      Pattern: $(AUTH_MODULE_DLL_PATTERN)
      signConfigType: inlineSignParams
      inlineOperation: |
       [
           {
               "keyCode": "CP-230012",
               "operationSetCode": "SigntoolSign",
               "parameters": [
                   {
                       "parameterName": "OpusName",
                       "parameterValue": "Microsoft"
                   },
                   {
                       "parameterName": "OpusInfo",
                       "parameterValue": "http://www.microsoft.com"
                   },
                   {
                       "parameterName": "FileDigest",
                       "parameterValue": "/fd \"SHA256\""
                   },
                   {
                       "parameterName": "PageHash",
                       "parameterValue": "/NPH"
                   },
                   {
                       "parameterName": "TimeStamp",
                       "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                   }
               ],
               "toolName": "sign",
               "toolVersion": "1.0"
           },
           {
               "keyCode": "CP-230012",
               "operationSetCode": "SigntoolVerify",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           }
       ]
      SessionTimeout: 20
  
  - task: PowerShell@2
    displayName: 'Pack Auth Module'
    inputs:
      targetType: 'inline'
      pwsh: true
      script: |
        pwsh $(System.DefaultWorkingDirectory)/tools/PackModule.ps1 -Module $(AUTH_MODULE_NAME) -ArtifactsLocation $(Build.ArtifactStagingDirectory)
  
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP NuGet CodeSigning'
    enabled: true
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet (AKV)'
      FolderPath: '$(Build.ArtifactStagingDirectory)\$(AUTH_MODULE_NAME)'
      Pattern: 'Microsoft.Graph.$(AUTH_MODULE_NAME)*.nupkg'
      signConfigType: inlineSignParams
      inlineOperation: |
            [
                {
                    "keyCode": "CP-401405",
                    "operationSetCode": "NuGetSign",
                    "parameters": [ ],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                },
                {
                    "keyCode": "CP-401405",
                    "operationSetCode": "NuGetVerify",
                    "parameters": [ ],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                }
            ]
      SessionTimeout: 20

  - task: NuGetCommand@2
    displayName: 'NuGet Publish To Local Build Feed'
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)\$(AUTH_MODULE_NAME)\Microsoft.Graph.$(AUTH_MODULE_NAME)*.nupkg'
      publishVstsFeed: '0985d294-5762-4bc2-a565-161ef349ca3e/edc337b9-e5ea-49dd-a2cb-e8d66668ca57'
      allowPackageConflicts: true

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact Microsoft.Graph.Authentication.nupkg'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(AUTH_MODULE_NAME)'
      ArtifactName: 'drop'
      publishLocation: 'Container'