# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 2.x'
      inputs:
        debugMode: false
        version: 2.x

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 3.x'
      inputs:
        debugMode: false
        version: 3.x

    - task: NuGetToolInstaller@1
      displayName: 'Install Nuget 5.7'
      inputs:
         versionSpec: 5.7.0
         checkLatest: false # Optional

    - task: PowerShell@2
      displayName: 'Install Powershell Core'
      inputs:
        targetType: inline
        script: |
          dotnet tool update --global PowerShell
          pwsh

    - task: PowerShell@2
      displayName: 'Version Check'
      inputs:
        targetType: inline
        pwsh: true
        script: |
          Write-Host $PSVersionTable.PSVersion
          Write-Host $host.Version
          Write-Host (Get-Host).Version

    - task: NodeTool@0
      displayName: 'Install NodeJs 13.14.0'
      inputs:
        versionSpec: '13.14.0' 
        checkLatest: false # Optional

    - task: Npm@1
      displayName: 'Install AutoRest'
      inputs:
        command: 'custom'
        customCommand: 'install -g autorest'

    - task: PowerShell@2
      displayName: 'Set Environment Variables'
      inputs:
        targetType: inline
        pwsh: true
        script: |
           npm config set node-options:max-old-space-size=16384
           $Env:NODE_OPTIONS="--max_old_space_size=16384"