# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 2.x'
      inputs:
        debugMode: false
        version: 2.x

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 3.x'
      inputs:
        debugMode: false
        version: 3.x

    - task: NodeTool@0
      displayName: 'Install NodeJs 13.14.0'
      inputs:
        versionSpec: '13.14.0' 
        checkLatest: false # Optional

    - task: Npm@1
      displayName: 'Install AutoRest'
      inputs:
        command: 'custom'
        customCommand: 'install -g autorest'

    - task: NuGetToolInstaller@1
      displayName: 'Install Nuget 5.7'
      inputs:
         versionSpec: 5.7.0
         checkLatest: false # Optional

    - task: PowerShell@2
      displayName: 'Install Powershell Core'
      inputs:
        targetType: inline
        script: |
          dotnet tool update --global PowerShell
          pwsh

    - task: PowerShell@2
      displayName: 'Test For Powershell'
      inputs:
        targetType: inline
        pwsh: true
        script: |
          pwsh
          pwsh $(System.DefaultWorkingDirectory)/tools/UpdateOpenApi.ps1
          Write-Host $pid
