# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 2.x'
      inputs:
        debugMode: false
        version: 2.x

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 3.x'
      inputs:
        debugMode: false
        version: 3.x

    - task: NuGetToolInstaller@1
      displayName: 'Install Nuget 5.7'
      inputs:
         versionSpec: 5.7.0
         checkLatest: false # Optional

    - task: NuGetAuthenticate@0

    - task: PowerShell@2
      displayName: 'Install Powershell Core'
      inputs:
        targetType: inline
        script: |
          dotnet tool update --global PowerShell
          pwsh

    - task: PowerShell@2
      displayName: 'Version Check'
      inputs:
        targetType: inline
        pwsh: true
        script: |
          Write-Host $PSVersionTable.PSVersion
          Write-Host $host.Version
          Write-Host (Get-Host).Version

    - task: NodeTool@0
      displayName: 'Install NodeJs 14.11.0'
      inputs:
        versionSpec: '14.11.0' 
        checkLatest: true # Optional

    - task: Npm@1
      displayName: 'Install AutoRest'
      inputs:
        command: 'custom'
        customCommand: 'install -g autorest@beta'