# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
pool: MsGraphDevXAzureAgents

variables:
  Branch: 'weeklyOpenApiDocsDownload'
  BaseBranch: 'dev'
  AUTH_MODULE_NAME: 'Authentication'
  AUTH_MODULE_PATH: 'src\Authentication\Authentication'
  AUTH_MODULE_DLL_PATTERN: 'Microsoft.Graph.Authentication.dll'
  MODULE_DLL_PATTERN: 'Microsoft.Graph.Authentication.dll'
  MODULE_PREFIX: 'Microsoft.Graph'
  ROLLUP_MODULE_NAME: 'Graph'
  ROLLUP_MODULE_PATH: 'src/Graph/Graph'
  WORKLOAD_MODULE_PATH: 'src'
  Api_Key: 'Api_Key'
  EnableSigning: true
  BUILDNUMBER: -1

schedules:
- cron: "0 0 * * WED" # Run Every Wednesday
  displayName: "Weekly OpenApiDocs Download and PR"
  branches: 
    include:
    - dev
  always: true

stages:
  - stage: DownloadOpenAPIDocs
    displayName: 'Download OpenAPI Docs'
    jobs:
    - template: ./download-openapidocs-template.yml
      parameters:
        Branch: $(Branch)
        BaseBranch: $(BaseBranch)

  - stage: GenerateModules
    displayName: 'Generate Modules (Microsoft.Graph.*)'
    jobs:
    - template: ./generate-modules-template.yml
      parameters:
        Api_Key: $(Api_Key)
        MODULE_PREFIX: $(MODULE_PREFIX)
        WORKLOAD_MODULE_PATH: $(WORKLOAD_MODULE_PATH)
        AUTH_MODULE_PATH: $(AUTH_MODULE_PATH)
        AUTH_MODULE_DLL_PATTERN: $(AUTH_MODULE_DLL_PATTERN)
        EnableSigning: true
        BUILDNUMBER: $(BUILDNUMBER)
        CHECKOUT_BRANCH: stageDependencies.DownloadOpenAPIDocs.outputs['MsGraphPSSDKDownloadOpenAPIDocs.ComputeBranch.Branch']